name: smsml-tensorflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - tensorflow==2.13.0
    - mlflow==2.19.0
    - scikit-learn==1.3.0
    - pandas==2.1.0
    - numpy==1.24.0
    - cloudpickle==3.1.0